version:0.2

phases: 
  build: 
    commands: 
       - echo Entered the build phase
       - mvn clean package
  post_build:
    commands:
       - echo Build completed successfully
       
artificats:
   files:
     - target/springboot-elastic-beanstalk.jar
   discard-paths: yes